// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGFncYUMIH5kO0mHzuIZxmqY96a_iHrzQ',
    appId: '1:873493013458:web:ac9c7c7fc3701e41799e0b',
    messagingSenderId: '873493013458',
    projectId: 'project-vidya-da4c2',
    authDomain: 'project-vidya-da4c2.firebaseapp.com',
    storageBucket: 'project-vidya-da4c2.appspot.com',
    measurementId: 'G-TF7KKMTFNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzJLjvuUbPI20XupI7JQngK0KnMxb3I4',
    appId: '1:873493013458:android:2e415646e1ac390e799e0b',
    messagingSenderId: '873493013458',
    projectId: 'project-vidya-da4c2',
    storageBucket: 'project-vidya-da4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnruwVLb2JVp9lSXvW5uxyyKL3gqNyA9M',
    appId: '1:873493013458:ios:1c90d91759aa873c799e0b',
    messagingSenderId: '873493013458',
    projectId: 'project-vidya-da4c2',
    storageBucket: 'project-vidya-da4c2.appspot.com',
    iosBundleId: 'com.example.projectVidya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnruwVLb2JVp9lSXvW5uxyyKL3gqNyA9M',
    appId: '1:873493013458:ios:499f3b072cf6172c799e0b',
    messagingSenderId: '873493013458',
    projectId: 'project-vidya-da4c2',
    storageBucket: 'project-vidya-da4c2.appspot.com',
    iosBundleId: 'com.example.projectVidya.RunnerTests',
  );
}
